#!/bin/bash

SYS1=$1
SYS1_POSTFIX=$2
SYS2=$3
SYS2_POSTFIX=$4
SEED1=$5
SEED2=$6
SEED3=$7
PREDICTIONS_PATH="../predictions/"



echo "$SYS1${SYS1_POSTFIX} - $SYS2${SYS2_POSTFIX}, with seeds: $SEED1 $SEED2 $SEED3"

python stats.py 4 -system1 \
    "$PREDICTIONS_PATH/${SYS1}_$SEED1${SYS1_POSTFIX}" \
    "$PREDICTIONS_PATH/${SYS1}_$SEED2${SYS1_POSTFIX}" \
    "$PREDICTIONS_PATH/${SYS1}_$SEED3${SYS1_POSTFIX}" \
    -system2 \
    "$PREDICTIONS_PATH/${SYS2}_$SEED1${SYS2_POSTFIX}" \
    "$PREDICTIONS_PATH/${SYS2}_$SEED2${SYS2_POSTFIX}" \
    "$PREDICTIONS_PATH/${SYS2}_$SEED3${SYS2_POSTFIX}" \