#!/usr/bin/env python3

import re
from struct import unpack
import numpy as np
from PIL import Image
import sys
import matplotlib.pyplot as plt

from utils import load_rgb_img 

def readPFM(file): 
    with open(file, "rb") as f:
        # Line 1: PF=>RGB (3 channels), Pf=>Greyscale (1 channel)
        type = f.readline().decode('latin-1')
        if "PF" in type:
            channels = 3
        elif "Pf" in type:
            channels = 1
        else:
            print("error : " + type)
            return None 
        # Line 2: width height
        line = f.readline().decode('latin-1')
        width, height = re.findall('\d+', line)
        width = int(width)
        height = int(height)

            # Line 3: +ve number means big endian, negative means little endian
        line = f.readline().decode('latin-1')
        BigEndian = True
        if "-" in line:
            BigEndian = False
        # Slurp all binary data
        samples = width * height * channels
        buffer = f.read(samples * 4)
        # Unpack floats with appropriate endianness
        if BigEndian:
            fmt = ">"
        else:
            fmt = "<"
        fmt = fmt + str(samples) + "f"
        img = unpack(fmt, buffer)
        img = np.reshape(img, (height, width))
        img = np.flipud(img)

    return img


na = readPFM(sys.argv[1])
print(na)
if not na:
    na = load_rgb_img(sys.argv[1])/256
print(sys.argv[2] + ".png")
plt.imsave(sys.argv[2] + ".png", na, vmin=0)

